#!/usr/bin/env python3
"""scripts/python/build_PRJNA608223_manifest.py

Merge an ENA filereport TSV (run_accession, fastq_ftp, fastq_md5, fastq_bytes)
with locally-computed SHA-256s into the frozen manifest format used by
data/snapshots/PRJNA608223/frozen_manifest.tsv.

Either input is optional. Whichever columns are not provided are written as
the literal token "pending" so downstream verifiers can tell what is known.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


def load_ena(path: Path) -> dict:
    rows = {}
    if not path:
        return rows
    with open(path) as f:
        for r in csv.DictReader(f, delimiter="\t"):
            urls = r["fastq_ftp"].split(";")
            md5s = r.get("fastq_md5", "").split(";")
            bs   = r.get("fastq_bytes", "").split(";")
            for u, m, b in zip(urls, md5s, bs):
                fn = u.split("/")[-1]
                rows[fn] = {"run": r["run_accession"], "md5": m or "pending",
                            "bytes": b or "pending"}
    return rows


def load_sha(path: Path) -> dict:
    rows = {}
    if not path:
        return rows
    with open(path) as f:
        for line in f:
            parts = line.split()
            if len(parts) != 2:
                continue
            sha, fn = parts
            rows[Path(fn).name] = sha
    return rows


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--ena", type=Path, default=None,
                   help="ENA filereport TSV (cols: run_accession,fastq_ftp,fastq_md5,fastq_bytes)")
    p.add_argument("--sha", type=Path, default=None,
                   help="local sha256sum output (cols: <sha>  <path>)")
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()

    ena = load_ena(args.ena)
    sha = load_sha(args.sha)

    files = sorted(set(list(ena) + list(sha)))
    if not files:
        print("ERROR: neither --ena nor --sha produced any rows", file=sys.stderr)
        return 1

    with open(args.out, "w") as f:
        f.write("# data/snapshots/PRJNA608223/frozen_manifest.tsv\n")
        f.write("# Generated by scripts/python/build_PRJNA608223_manifest.py\n")
        f.write("# Columns: run_accession, file, byte_size, md5, sha256\n")
        f.write("run_accession\tfile\tbyte_size\tmd5\tsha256\n")
        for fn in files:
            run = ena.get(fn, {}).get("run", "pending")
            bs  = ena.get(fn, {}).get("bytes", "pending")
            md5 = ena.get(fn, {}).get("md5", "pending")
            s   = sha.get(fn, "pending")
            f.write(f"{run}\t{fn}\t{bs}\t{md5}\t{s}\n")

    print(f"Wrote {args.out} with {len(files)} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
